[Interface]
PrivateKey = YI/IzZSSAPf+LXJqvtMYNtT7bkhaq9+BiSQHZDNJX2U=
Address = 10.66.0.2/32
DNS = 8.8.8.8

[Peer]
PublicKey = YrF+RUdTviJk6PN+BpefmUP9NipJJdTYdHvP2nDP2hI=
Endpoint = 93.77.182.234:51820
AllowedIPs = 10.10.2.0/24
PersistentKeepalive = 25
